version: "3.9"

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"  # Correctly formatted as a list
    environment:
      - DEBUG=True
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"  # Fixed the port syntax
